In [1]:
import pandas as pd
import numpy as np
from pandas import DataFrame
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model

In [6]:
df=pd.read_csv('/content/house pricing.csv')

In [7]:
df

area  beadrooms  age   price
0  2600        3.0   20  550000
1  3600        4.0   15  565000
2  3200        NaN   18  610000
3  3600        3.0   30  595000
4  4000        5.0    8  760000
5  4500        6.0    8  810000

In [13]:
new=df.beadrooms.fillna(0)

In [20]:
df['beadrooms']=new

In [21]:
df

area  beadrooms  age   price
0  2600        3.0   20  550000
1  3600        4.0   15  565000
2  3200        0.0   18  610000
3  3600        3.0   30  595000
4  4000        5.0    8  760000
5  4500        6.0    8  810000

In [22]:
model=linear_model.LinearRegression()

In [28]:
model.fit(df.drop('price',axis='columns'),df.price)

LinearRegression()

In [30]:
model.predict([[3000,3,5]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([642099.80937872])

In [31]:
model.coef_

array([  109.63211464, -1023.95430416, -4974.48397959])

In [32]:
model.intercept_

341147.74827592954

In [33]:
#y=m*area+m2*beadroom+m3*age+b

In [34]:
109.63211464*3000+-1023.95430416*3+-4974.48397959*5+341147.74827592954

642099.8093854995

In [35]:
ned_df=pd.read_csv("/content/experinc salry.csv")

In [36]:
ned_df

experince  test_score  intv score  salary
0       NaN         8.0           9   50000
1       NaN         8.0           6   45000
2      five         6.0           7   60000
3       two        10.0          10   65000
4     seven         9.0           6   70000
5     three         7.0          10   62000
6       ten         NaN           7   72000
7    eleven         7.0           8   80000

In [75]:
ned_df.experince=ned_df.experince.fillna("zero")

In [76]:
pip install word2number

In [72]:
from word2number import w2n

In [77]:
ned_df.experince=ned_df.experince.apply(w2n.word_to_num)


In [78]:
ned_df

experince  test_score  intv score  salary
0          0         8.0           9   50000
1          0         8.0           6   45000
2          5         6.0           7   60000
3          2        10.0          10   65000
4          7         9.0           6   70000
5          3         7.0          10   62000
6         10         NaN           7   72000
7         11         7.0           8   80000

In [83]:
ned_df['test_score'].mean()

7.857142857142857

In [85]:
ned_df['test_score']=ned_df['test_score'].fillna(ned_df['test_score'].mean())

In [86]:
ned_df

experince  test_score  intv score  salary
0          0    8.000000           9   50000
1          0    8.000000           6   45000
2          5    6.000000           7   60000
3          2   10.000000          10   65000
4          7    9.000000           6   70000
5          3    7.000000          10   62000
6         10    7.857143           7   72000
7         11    7.000000           8   80000

In [87]:
models=linear_model.LinearRegression()

In [88]:
models.fit(ned_df[['experince','test_score','intv score']],ned_df.salary)

LinearRegression()

In [89]:
models.predict([[2,9,6]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([53290.89255945])